apiVersion: kobe.semagrow.org/v1alpha1
kind: Benchmark
metadata:
  name: geographica-rw
spec:
  datasets:
    - name: gg2rw
      files:
        - url: https://users.iit.demokritos.gr/~antru/dumps/geographica2/gg2-rw.tar.gz
      templateRef: strabontemplate
  queries:
    - name: GGRWQ-01
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (geof:boundary(?o1) AS ?ret) 
      WHERE { 
        ?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1 .
      }'

    - name: GGRWQ-02
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (geof:envelope(?o1) AS ?ret) 
      WHERE { 
        ?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1 .
      }'

    - name: GGRWQ-03
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (geof:convexHull(?o1) AS ?ret) 
      WHERE { 
        ?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1 .
      }'

    - name: GGRWQ-04
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (geof:buffer(?o1,0.04) AS ?ret) 
      WHERE { 
        ?s1 <http://www.geonames.org/ontology#asWKT> ?o1 .
      }'

    - name: GGRWQ-05
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (geof:buffer(?o1,0.04) AS ?ret) 
      WHERE { 
        ?s1 <http://linkedgeodata.org/ontology/asWKT> ?o1 .
      }'

    - name: GGRWQ-06
      language: sparql
      queryString: 'PREFIX geof: <http://www.opengis.net/def/function/geosparql/> 

      SELECT (ext:area(?o1) AS ?ret) 
      WHERE { 
        ?s1 <http://geo.linkedopendata.gr/corine/ontology#asWKT> ?o1 .
      }'